---
- name: Criação e registro de pares de chave
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/global.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"
  
  tasks:
    - name: configura bibliotecas Python
      import_tasks: setup-python.yml
      - name: Verificação da existência de chave no EC2
      amazon.aws.ec2_key:
        name: "{{ access_key }}"
        region: "{{ aws_region }}"
        force: false
      register: existing_ec2_key_result

    - name: Recuperação do conteúdo da chave privada
      ansible.builtin.copy:
        content: "{{ lookup('amazon.aws.aws_secret', access_key, region=aws_region) }}"
        dest: "{{ playbook_dir }}/{{ access_key }}"
        mode: 0600
      when: existing_ec2_key_result.msg == "key pair already exists"
      register: private_key
