---
- name: Criação de VPC, Subnet, Internet gateway, Route table, Security group
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars_files:
    - vars/global.yml
    - vars/vpc.yml
    
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"

  tasks:
  - name: configura bibliotecas Python
    import_tasks: setup-python.yml
    
  - name: Criação de VPC
    ec2_vpc_net:
      region: "{{ aws_region }}"
      name: "{{ vpc_name }}" 
      cidr_block: "{{ vpcCidrBlock }}"      
      dns_support: yes
      dns_hostnames: yes
      tenancy: default
      tags:
        Name: "{{ vpc_name }}"
    register: vpc_result
