name: devops-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm --prefix frontend install
    - run: npm --prefix frontend run build
    - uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: frontend/build
    - run: aws s3 cp frontend/build s3://devops-wapj --recursive --acl public-read
