name: devops-pipeline
#on:
  #push:
    #branches: [ main ]
on:
  workflow_dispatch
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm --prefix frontend install
    - run: npm --prefix frontend run build
    - uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: frontend/build
env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
jobs:
…
   deploy:
- uses: actions/download-artifact@v2
      with:
        name: deploy
        path: frontend/build
      - run: aws s3 cp frontend/build s3://devops-cyo --recursive --acl public-read
